package vistas;

import controlador.UCCPerson;
import dominio.Customer;
import dominio.Person;

/**
 *
 * @author Isra
 */
public class CustomerView extends javax.swing.JDialog {
    private int viewState;
    private Person customer;

    public CustomerView(java.awt.Frame parent, boolean modal,int viewState,Person customer) {
        super(parent, modal);
        this.viewState = viewState;
        this.customer = customer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        clientIdentificationTypeCB = new javax.swing.JComboBox();
        clientIdentificationTxt = new javax.swing.JTextField();
        clientEmailTxt = new javax.swing.JTextField();
        clientProfessionCB = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientAddressTA = new javax.swing.JTextArea();
        clientFirstNameTxt = new javax.swing.JTextField();
        clientLastNameTxt = new javax.swing.JTextField();
        clientTypeCB = new javax.swing.JComboBox();
        clientSaveBT = new javax.swing.JButton();
        clientCloseBT = new javax.swing.JButton();
        clientBornDateDC = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Tipo:");

        jLabel4.setText("Fecha de nacimiento:");

        jLabel5.setText("Tipo de identificación:");

        jLabel6.setText("Identificación:");

        jLabel7.setText("Correo electrónico:");

        jLabel8.setText("Profesión:");

        jLabel9.setText("Dirección:");

        clientIdentificationTypeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "CÉDULA", "RUC", "PASAPORTE" }));

        clientEmailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientEmailTxtActionPerformed(evt);
            }
        });

        clientProfessionCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "Comerciante", "Ing. en Sistemas", "Ing. Administración de Empresas", "Economista", "Contador(a)", "Arquitecto", "Ing. Civil", "Doctor(a)", " " }));

        clientAddressTA.setColumns(20);
        clientAddressTA.setRows(5);
        jScrollPane1.setViewportView(clientAddressTA);

        clientTypeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "Cliente", "Empleado", "Usuario", " " }));

        clientSaveBT.setText("GUARDAR");
        clientSaveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientSaveBTActionPerformed(evt);
            }
        });

        clientCloseBT.setText("CERRAR");
        clientCloseBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientCloseBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clientTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clientFirstNameTxt)
                            .addComponent(clientLastNameTxt)
                            .addComponent(clientIdentificationTypeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientIdentificationTxt)
                            .addComponent(clientEmailTxt)
                            .addComponent(clientProfessionCB, 0, 198, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(clientBornDateDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clientSaveBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientCloseBT)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clientFirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clientLastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clientTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clientBornDateDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(clientIdentificationTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(clientIdentificationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(clientEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(clientProfessionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientSaveBT)
                    .addComponent(clientCloseBT))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clientEmailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientEmailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientEmailTxtActionPerformed

    private void clientSaveBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientSaveBTActionPerformed
        // TODO add your handling code here:
        UCCPerson uccPerson = new UCCPerson();
        if(viewState == 1){
            uccPerson.savePerson(this,viewState,new Customer());
            
        }else if(viewState ==2){
            System.out.println("AQUI ENTRO PAERA EDITAR");
            uccPerson.updatePerson(this, viewState, customer);
        }else if(viewState == 3){
            uccPerson.removePerson(this);
            
        }
        
        
    }//GEN-LAST:event_clientSaveBTActionPerformed

    private void clientCloseBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientCloseBTActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_clientCloseBTActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea clientAddressTA;
    public org.jdesktop.swingx.JXDatePicker clientBornDateDC;
    public javax.swing.JButton clientCloseBT;
    public javax.swing.JTextField clientEmailTxt;
    public javax.swing.JTextField clientFirstNameTxt;
    public javax.swing.JTextField clientIdentificationTxt;
    public javax.swing.JComboBox clientIdentificationTypeCB;
    public javax.swing.JTextField clientLastNameTxt;
    public javax.swing.JComboBox clientProfessionCB;
    public javax.swing.JButton clientSaveBT;
    public javax.swing.JComboBox clientTypeCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
